spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123qwert
    url: jdbc:mysql://127.0.0.1:3306/cloud?characterEncoding=utf-8
  jpa:
    show-sql: true
server:
  port: 8763

env:
  dev

girl:
  name: lanlan
  age: 19

